#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using AetherNexus.FoundationPlatform.AetherInspector;
using UnityEditor;
using UnityEngine;

namespace AetherNexus.FoundationPlatform.Editor.Utilities
{
    public enum HierarchyRoot
    {
        Data = 0,
        Scripts = 1
    }

    public enum HierarchyBucket
    {
        Domains = 0,
        Shared = 1,
        Global = 2,
        AutoGenerated = 3
    }

    public enum DataFolderMappingPathClassification
    {
        Mapped = 0,
        Exempt = 1,
        Violation = 2
    }

    [CreateAssetMenu(fileName = "DataFolderMappingConfig", menuName = "Foundation/Data Folder Mapping Config")]
    public class DataFolderMappingConfig : ScriptableObject
    {
        public const string DefaultAssetPath = "Assets/Data/Global/Authoring/DataFolderMappingConfig.asset";
        public const string CentralAuthoringProjectConfigAssetPath = "Assets/Data/Global/Authoring/CentralAuthoringProjectConfig.asset";
        private const string DataDomainsRoot = "Assets/Data/Domains";
        private const string DataSharedRoot = "Assets/Data/Shared";
        private const string DataGlobalRoot = "Assets/Data/Global";

        [SerializeField]
        [InspectorName("Hierarchy Domains")]
        private List<string> domains = new();

        [SerializeField]
        [InspectorName("Data Shared Subfolders")]
        private List<string> dataSharedSubfolders = new();

        [SerializeField]
        [InspectorName("Data Global Subfolders")]
        private List<string> dataGlobalSubfolders = new();

        [SerializeField]
        [InspectorName("Required Asset Folder Roots")]
        [Tooltip("Authoring-only. Each path must be a folder under Assets/. Empty list disables this check. Validated in GameEngineCore Hub validation.")]
        private List<string> requiredAssetFolderRoots = new();

        public IReadOnlyList<string> Domains => domains;
        public IReadOnlyList<string> DataSharedSubfolders => dataSharedSubfolders;
        public IReadOnlyList<string> DataGlobalSubfolders => dataGlobalSubfolders;
        public IReadOnlyList<string> RequiredAssetFolderRoots => requiredAssetFolderRoots;

        [Button(ButtonSizes.Medium)]
        private void PopulateFromFileSystemState()
        {
            domains = GetTopLevelFolderNames(DataDomainsRoot);
            dataSharedSubfolders = GetTopLevelFolderNames(DataSharedRoot);
            dataGlobalSubfolders = GetTopLevelFolderNames(DataGlobalRoot);

            EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }

        public IReadOnlyList<string> GetConfiguredDomains()
        {
            var result = new List<string>();
            for (int i = 0; i < domains.Count; i++)
            {
                string domain = domains[i];
                if (string.IsNullOrWhiteSpace(domain))
                    continue;
                string normalized = domain.Trim();
                bool exists = false;
                for (int r = 0; r < result.Count; r++)
                {
                    if (string.Equals(result[r], normalized, StringComparison.OrdinalIgnoreCase))
                    {
                        exists = true;
                        break;
                    }
                }

                if (!exists)
                    result.Add(normalized);
            }

            return result;
        }

        public bool IsKnownDomain(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                return false;

            string trimmed = name.Trim();
            for (int i = 0; i < domains.Count; i++)
            {
                string domain = domains[i];
                if (string.IsNullOrWhiteSpace(domain))
                    continue;
                if (string.Equals(domain.Trim(), trimmed, StringComparison.OrdinalIgnoreCase))
                    return true;
            }

            return false;
        }

        public IReadOnlyList<Type> GetAllMappedTypes()
        {
            Dictionary<Type, List<string>> mappings = BuildManifestPatternMap();
            return new List<Type>(mappings.Keys);
        }

        public IReadOnlyList<string> GetPatternsForType(Type requestedType)
        {
            var result = new List<string>();
            if (requestedType == null)
                return result;

            Dictionary<Type, List<string>> mappings = BuildManifestPatternMap();
            foreach (KeyValuePair<Type, List<string>> mapping in mappings)
            {
                Type mappedType = mapping.Key;
                if (mappedType == null)
                    continue;
                if (mappedType != requestedType && !mappedType.IsAssignableFrom(requestedType))
                    continue;

                List<string> patterns = mapping.Value;
                for (int p = 0; p < patterns.Count; p++)
                {
                    string pattern = patterns[p];
                    if (string.IsNullOrWhiteSpace(pattern))
                        continue;
                    result.Add(DataFolderMappingPathUtility.NormalizeAssetPath(pattern.Trim()));
                }
                break;
            }

            return result;
        }

        public IReadOnlyList<string> ResolveConcreteFoldersForType(Type requestedType)
        {
            var resolved = new List<string>();
            IReadOnlyList<string> patterns = GetPatternsForType(requestedType);
            for (int i = 0; i < patterns.Count; i++)
            {
                IEnumerable<string> folders = HierarchyPatternMatcher.ExpandConcreteFolders(patterns[i], domains);
                foreach (string folder in folders)
                {
                    if (!AssetDatabase.IsValidFolder(folder))
                        continue;
                    bool exists = false;
                    for (int e = 0; e < resolved.Count; e++)
                    {
                        if (string.Equals(resolved[e], folder, StringComparison.OrdinalIgnoreCase))
                        {
                            exists = true;
                            break;
                        }
                    }

                    if (!exists)
                        resolved.Add(folder);
                }
            }

            return resolved;
        }

        public bool TypeHasAnyWildcardPattern(Type requestedType)
        {
            IReadOnlyList<string> patterns = GetPatternsForType(requestedType);
            for (int i = 0; i < patterns.Count; i++)
            {
                string pattern = patterns[i];
                if (string.IsNullOrEmpty(pattern))
                    continue;
                if (pattern.IndexOf('*') >= 0)
                    return true;
            }

            return false;
        }

        public bool TryGetFolderForType(Type requestedType, out string folderPath, out string reason)
        {
            folderPath = null;
            reason = string.Empty;

            if (requestedType == null)
            {
                reason = "No field type resolved.";
                return false;
            }

            if (!typeof(UnityEngine.Object).IsAssignableFrom(requestedType))
            {
                reason = "Field is not a Unity object reference.";
                return false;
            }

            IReadOnlyList<string> concrete = ResolveConcreteFoldersForType(requestedType);
            if (concrete.Count == 1)
            {
                folderPath = concrete[0];
                return true;
            }
            if (concrete.Count > 1)
            {
                reason = $"Multiple mapped folders found for '{requestedType.FullName}'.";
                return false;
            }

            reason = $"No Data folder mapping found for '{requestedType.FullName}'.";
            return false;
        }

        public bool TryClassifyAssetPathForType(
            Type requestedType,
            string assetPath,
            IReadOnlyList<string> exemptRootFolders,
            out DataFolderMappingPathClassification classification,
            out string mappedFolderPath,
            out string reason)
        {
            classification = DataFolderMappingPathClassification.Violation;
            mappedFolderPath = null;
            reason = string.Empty;

            if (string.IsNullOrEmpty(assetPath))
            {
                reason = "Asset path is empty.";
                return false;
            }

            IReadOnlyList<string> patterns = GetPatternsForType(requestedType);
            if (patterns.Count == 0)
            {
                reason = $"No Data folder mapping found for '{requestedType.FullName}'.";
                return false;
            }

            string normalizedAssetPath = DataFolderMappingPathUtility.NormalizeAssetPath(assetPath);
            bool mapped = false;
            string unknownDomainReason = string.Empty;
            for (int i = 0; i < patterns.Count; i++)
            {
                string pattern = patterns[i];
                if (string.IsNullOrWhiteSpace(pattern))
                    continue;

                if (HierarchyPatternMatcher.Match(normalizedAssetPath, pattern, domains, out _, out string matchReason))
                {
                    mapped = true;
                    break;
                }

                if (!string.IsNullOrEmpty(matchReason) && matchReason.IndexOf("UnknownDomain", StringComparison.OrdinalIgnoreCase) >= 0)
                    unknownDomainReason = matchReason;
            }

            if (mapped)
            {
                classification = DataFolderMappingPathClassification.Mapped;
                IReadOnlyList<string> concrete = ResolveConcreteFoldersForType(requestedType);
                if (concrete.Count == 1)
                    mappedFolderPath = concrete[0];
                return true;
            }

            if (DataFolderMappingPathUtility.IsPathUnderAnyFolder(assetPath, exemptRootFolders))
            {
                classification = DataFolderMappingPathClassification.Exempt;
                reason = "Asset is outside mapped patterns but inside an exemption marker folder.";
                return true;
            }

            classification = DataFolderMappingPathClassification.Violation;
            reason = string.IsNullOrEmpty(unknownDomainReason)
                ? "Asset is outside mapped patterns and not covered by exemption marker scope."
                : unknownDomainReason;
            return true;
        }

        public bool TryClassifyHierarchyPath(
            string assetPath,
            out HierarchyRoot root,
            out HierarchyBucket bucket,
            out string domain,
            out string reason)
        {
            root = HierarchyRoot.Data;
            bucket = HierarchyBucket.Domains;
            domain = string.Empty;
            reason = string.Empty;

            if (string.IsNullOrWhiteSpace(assetPath))
            {
                reason = "Asset path is empty.";
                return false;
            }

            string normalized = DataFolderMappingPathUtility.NormalizeAssetPath(assetPath);
            string[] segments = normalized.Split('/');
            if (segments.Length < 3 || !string.Equals(segments[0], "Assets", StringComparison.OrdinalIgnoreCase))
            {
                reason = "Asset path must be under Assets/ root.";
                return false;
            }

            if (string.Equals(segments[1], "Data", StringComparison.OrdinalIgnoreCase))
            {
                root = HierarchyRoot.Data;
                return TryClassifyDataHierarchyPath(segments, out bucket, out domain, out reason);
            }

            if (string.Equals(segments[1], "Scripts", StringComparison.OrdinalIgnoreCase))
            {
                root = HierarchyRoot.Scripts;
                return TryClassifyScriptsHierarchyPath(segments, out bucket, out domain, out reason);
            }

            reason = "Asset path must be under Assets/Data or Assets/Scripts.";
            return false;
        }

        public void AppendRequiredFolderRootIssues(IList<string> messages)
        {
            if (messages == null)
                throw new ArgumentNullException(nameof(messages));
            if (requiredAssetFolderRoots == null || requiredAssetFolderRoots.Count == 0)
                return;

            const string assetsPrefix = "Assets/";
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            for (int i = 0; i < requiredAssetFolderRoots.Count; i++)
            {
                string raw = requiredAssetFolderRoots[i];
                if (string.IsNullOrWhiteSpace(raw))
                    continue;

                string path = DataFolderMappingPathUtility.NormalizeAssetPath(raw.Trim());
                if (!seen.Add(path))
                    continue;

                if (!path.StartsWith(assetsPrefix, StringComparison.OrdinalIgnoreCase))
                {
                    messages.Add("[DataFolderMappingConfig] Required folder root must start with '" + assetsPrefix + "'. Got: '" + path + "'.");
                    continue;
                }

                if (!AssetDatabase.IsValidFolder(path))
                    messages.Add("[DataFolderMappingConfig] Required folder root does not exist or is not a folder: '" + path + "'.");
            }
        }

        public static DataFolderMappingConfig Load()
        {
            DataFolderMappingConfig config = AssetDatabase.LoadAssetAtPath<DataFolderMappingConfig>(DefaultAssetPath);
            if (config != null)
                return config;

            string[] guids = AssetDatabase.FindAssets("t:DataFolderMappingConfig");
            for (int i = 0; i < guids.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(guids[i]);
                config = AssetDatabase.LoadAssetAtPath<DataFolderMappingConfig>(path);
                if (config != null)
                    return config;
            }

            ScriptableObject centralConfig = AssetDatabase.LoadAssetAtPath<ScriptableObject>(CentralAuthoringProjectConfigAssetPath);
            if (centralConfig == null)
                return null;

            SerializedObject serialized = new SerializedObject(centralConfig);
            var snapshot = CreateInstance<DataFolderMappingConfig>();
            snapshot.hideFlags = HideFlags.HideAndDontSave;
            CopyStringListProperty(serialized, "domains", snapshot.domains);
            CopyStringListProperty(serialized, "dataSharedSubfolders", snapshot.dataSharedSubfolders);
            CopyStringListProperty(serialized, "dataGlobalSubfolders", snapshot.dataGlobalSubfolders);
            CopyStringListProperty(serialized, "requiredAssetFolderRoots", snapshot.requiredAssetFolderRoots);
            return snapshot;
        }

        private Dictionary<Type, List<string>> BuildManifestPatternMap()
        {
            var map = new Dictionary<Type, List<string>>();
            string[] manifestGuids = AssetDatabase.FindAssets("t:PackageIntegrationManifest");
            for (int i = 0; i < manifestGuids.Length; i++)
            {
                string manifestPath = AssetDatabase.GUIDToAssetPath(manifestGuids[i]);
                ScriptableObject manifest = AssetDatabase.LoadAssetAtPath<ScriptableObject>(manifestPath);
                if (manifest == null)
                    continue;

                SerializedObject so = new SerializedObject(manifest);
                SerializedProperty entries = so.FindProperty("typeMappings");
                if (entries == null || !entries.isArray)
                    continue;

                for (int e = 0; e < entries.arraySize; e++)
                {
                    SerializedProperty entry = entries.GetArrayElementAtIndex(e);
                    SerializedProperty typeScriptProp = entry.FindPropertyRelative("TypeScript");
                    MonoScript typeScript = typeScriptProp != null ? typeScriptProp.objectReferenceValue as MonoScript : null;
                    if (typeScript == null)
                        continue;

                    Type mappedType = typeScript.GetClass();
                    if (mappedType == null)
                        continue;

                    SerializedProperty patternsProp = entry.FindPropertyRelative("Patterns");
                    if (!map.TryGetValue(mappedType, out List<string> patternList))
                    {
                        patternList = new List<string>();
                        map.Add(mappedType, patternList);
                    }

                    if (patternsProp == null || !patternsProp.isArray)
                        continue;

                    for (int p = 0; p < patternsProp.arraySize; p++)
                    {
                        string raw = patternsProp.GetArrayElementAtIndex(p).stringValue;
                        if (string.IsNullOrWhiteSpace(raw))
                            continue;

                        string normalized = DataFolderMappingPathUtility.NormalizeAssetPath(raw.Trim());
                        bool exists = false;
                        for (int n = 0; n < patternList.Count; n++)
                        {
                            if (!string.Equals(patternList[n], normalized, StringComparison.OrdinalIgnoreCase))
                                continue;
                            exists = true;
                            break;
                        }

                        if (!exists)
                            patternList.Add(normalized);
                    }
                }
            }

            return map;
        }

        private static void CopyStringListProperty(SerializedObject source, string propertyName, List<string> destination)
        {
            destination.Clear();
            SerializedProperty prop = source.FindProperty(propertyName);
            if (prop == null || !prop.isArray)
                return;

            for (int i = 0; i < prop.arraySize; i++)
            {
                string value = prop.GetArrayElementAtIndex(i).stringValue;
                if (string.IsNullOrWhiteSpace(value))
                    continue;
                destination.Add(value.Trim());
            }
        }

        private static List<string> GetTopLevelFolderNames(string rootPath)
        {
            var result = new List<string>();
            if (string.IsNullOrEmpty(rootPath) || !AssetDatabase.IsValidFolder(rootPath))
                return result;

            string[] guids = AssetDatabase.FindAssets("t:DefaultAsset", new[] { rootPath });
            for (int i = 0; i < guids.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(guids[i]);
                if (!AssetDatabase.IsValidFolder(path))
                    continue;
                if (string.Equals(path, rootPath, StringComparison.OrdinalIgnoreCase))
                    continue;

                string relative = path.Substring(rootPath.Length).TrimStart('/');
                if (relative.IndexOf('/') >= 0)
                    continue;

                string folderName = System.IO.Path.GetFileName(path);
                if (string.IsNullOrWhiteSpace(folderName))
                    continue;

                bool exists = false;
                for (int e = 0; e < result.Count; e++)
                {
                    if (string.Equals(result[e], folderName, StringComparison.OrdinalIgnoreCase))
                    {
                        exists = true;
                        break;
                    }
                }

                if (!exists)
                    result.Add(folderName);
            }

            result.Sort(StringComparer.OrdinalIgnoreCase);
            return result;
        }

        private bool TryClassifyDataHierarchyPath(
            string[] segments,
            out HierarchyBucket bucket,
            out string domain,
            out string reason)
        {
            bucket = HierarchyBucket.Domains;
            domain = string.Empty;
            reason = string.Empty;

            string bucketSegment = segments[2];
            if (string.Equals(bucketSegment, "Domains", StringComparison.OrdinalIgnoreCase))
            {
                bucket = HierarchyBucket.Domains;
                if (segments.Length < 4)
                {
                    reason = "Data Domains path must include a domain folder.";
                    return false;
                }

                domain = segments[3];
                if (!IsKnownDomain(domain))
                {
                    reason = "Unknown Data domain: '" + domain + "'.";
                    return false;
                }

                return true;
            }

            if (string.Equals(bucketSegment, "Shared", StringComparison.OrdinalIgnoreCase))
            {
                bucket = HierarchyBucket.Shared;
                return ValidateDataBucketSubfolder(segments, dataSharedSubfolders, "Data/Shared", out reason);
            }

            if (string.Equals(bucketSegment, "Global", StringComparison.OrdinalIgnoreCase))
            {
                bucket = HierarchyBucket.Global;
                return ValidateDataBucketSubfolder(segments, dataGlobalSubfolders, "Data/Global", out reason);
            }

            reason = "Unsupported Data bucket: '" + bucketSegment + "'.";
            return false;
        }

        private bool TryClassifyScriptsHierarchyPath(
            string[] segments,
            out HierarchyBucket bucket,
            out string domain,
            out string reason)
        {
            bucket = HierarchyBucket.Domains;
            domain = string.Empty;
            reason = string.Empty;

            string bucketSegment = segments[2];
            if (string.Equals(bucketSegment, "Domains", StringComparison.OrdinalIgnoreCase))
            {
                bucket = HierarchyBucket.Domains;
                if (segments.Length < 4)
                {
                    reason = "Scripts Domains path must include a domain folder.";
                    return false;
                }

                domain = segments[3];
                if (!IsKnownDomain(domain))
                {
                    reason = "Unknown Scripts domain: '" + domain + "'.";
                    return false;
                }

                return true;
            }

            if (string.Equals(bucketSegment, "Shared", StringComparison.OrdinalIgnoreCase))
            {
                bucket = HierarchyBucket.Shared;
                return true;
            }

            if (string.Equals(bucketSegment, "Global", StringComparison.OrdinalIgnoreCase))
            {
                bucket = HierarchyBucket.Global;
                return true;
            }

            if (string.Equals(bucketSegment, "AutoGenerated", StringComparison.OrdinalIgnoreCase))
            {
                bucket = HierarchyBucket.AutoGenerated;
                return true;
            }

            reason = "Unsupported Scripts bucket: '" + bucketSegment + "'.";
            return false;
        }

        private static bool ValidateDataBucketSubfolder(
            string[] segments,
            IReadOnlyList<string> configuredSubfolders,
            string bucketLabel,
            out string reason)
        {
            reason = string.Empty;
            if (configuredSubfolders == null || configuredSubfolders.Count == 0 || segments.Length < 4)
                return true;

            string subfolder = segments[3];
            for (int i = 0; i < configuredSubfolders.Count; i++)
            {
                string configured = configuredSubfolders[i];
                if (string.IsNullOrWhiteSpace(configured))
                    continue;
                if (string.Equals(configured.Trim(), subfolder, StringComparison.OrdinalIgnoreCase))
                    return true;
            }

            reason = bucketLabel + " subfolder is not listed in config: '" + subfolder + "'.";
            return false;
        }
    }

    internal static class DataFolderMappingPathUtility
    {
        public static bool IsPathUnderAnyFolder(string assetPath, IReadOnlyList<string> folders)
        {
            if (folders == null || folders.Count == 0)
                return false;

            for (int i = 0; i < folders.Count; i++)
            {
                if (IsPathUnderFolder(assetPath, folders[i]))
                    return true;
            }

            return false;
        }

        public static bool IsPathUnderFolder(string assetPath, string folderPath)
        {
            if (string.IsNullOrEmpty(assetPath) || string.IsNullOrEmpty(folderPath))
                return false;

            string normalizedAsset = NormalizeAssetPath(assetPath);
            string normalizedFolder = NormalizeAssetPath(folderPath).TrimEnd('/');
            return normalizedAsset.StartsWith(normalizedFolder + "/", StringComparison.OrdinalIgnoreCase)
                   || string.Equals(normalizedAsset, normalizedFolder, StringComparison.OrdinalIgnoreCase);
        }

        public static string NormalizeAssetPath(string path)
        {
            return string.IsNullOrEmpty(path) ? string.Empty : path.Replace('\\', '/');
        }
    }

    public static class DataFolderMappingExemptionResolver
    {
        public static IReadOnlyList<string> DiscoverExemptRootFolders(DataFolderMappingConfig config)
        {
            string[] markerGuids = AssetDatabase.FindAssets("t:DataFolderExemptionMarker", new[] { "Assets" });
            var roots = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            for (int i = 0; i < markerGuids.Length; i++)
            {
                string markerPath = AssetDatabase.GUIDToAssetPath(markerGuids[i]);
                if (string.IsNullOrEmpty(markerPath))
                    continue;

                string folder = System.IO.Path.GetDirectoryName(markerPath);
                if (string.IsNullOrEmpty(folder))
                    continue;

                roots.Add(DataFolderMappingPathUtility.NormalizeAssetPath(folder));
            }

            return new List<string>(roots);
        }

        /// <summary>Discovers exempt root folders with no config.</summary>
        public static IReadOnlyList<string> DiscoverExemptRootFolders() => DiscoverExemptRootFolders(null);

        public static bool IsPathUnderExemptScope(string assetPath, IReadOnlyList<string> exemptRootFolders)
        {
            if (string.IsNullOrEmpty(assetPath))
                return false;

            IReadOnlyList<string> roots = exemptRootFolders ?? DiscoverExemptRootFolders();
            return DataFolderMappingPathUtility.IsPathUnderAnyFolder(assetPath, roots);
        }

        /// <summary>Checks the path against freshly-discovered exempt root folders.</summary>
        public static bool IsPathUnderExemptScope(string assetPath) => IsPathUnderExemptScope(assetPath, null);

        private static readonly Dictionary<Type, string> s_typeScriptPathCache = new();

        public static bool TryGetTypeScriptPath(Type type, out string scriptPath)
        {
            scriptPath = null;
            if (type == null)
                return false;

            if (s_typeScriptPathCache.TryGetValue(type, out scriptPath))
            {
                return scriptPath != null;
            }

            string[] guids = AssetDatabase.FindAssets(type.Name + " t:MonoScript");
            for (int i = 0; i < guids.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(guids[i]);
                MonoScript script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                if (script == null || script.GetClass() != type)
                    continue;

                scriptPath = DataFolderMappingPathUtility.NormalizeAssetPath(path);
                s_typeScriptPathCache[type] = scriptPath;
                return true;
            }

            s_typeScriptPathCache[type] = null;
            return false;
        }

        public static bool IsTypeScriptUnderExemptScope(Type type, IReadOnlyList<string> exemptRootFolders)
        {
            return TryGetTypeScriptPath(type, out string scriptPath)
                   && IsPathUnderExemptScope(scriptPath, exemptRootFolders);
        }

        /// <summary>Checks against freshly-discovered exempt root folders.</summary>
        public static bool IsTypeScriptUnderExemptScope(Type type) => IsTypeScriptUnderExemptScope(type, null);

        public static string ToAssetsRelativePath(string path)
        {
            string normalized = DataFolderMappingPathUtility.NormalizeAssetPath(path);
            if (string.IsNullOrEmpty(normalized))
                return string.Empty;

            int index = normalized.IndexOf("Assets/", StringComparison.OrdinalIgnoreCase);
            if (index < 0)
                return normalized;

            return normalized.Substring(index);
        }
    }
}
#endif
