#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Text;

namespace AetherNexus.FoundationPlatform.ComponentMenus.Editor
{
    /// <summary>
    /// Answers "where does this component go in <c>Add Component</c>". Two shapes only, per
    /// <c>docs/NAMING.md</c> section 4: one of Unity's own roots when the component does the same
    /// job as that category, otherwise <c>Framework Name / Category / Type</c>.
    /// </summary>
    internal static class ComponentMenuTaxonomy
    {
        /// <summary>Native Add Component roots a first-party component may file into. Nothing outside this list.</summary>
        internal static readonly string[] NativeRoots = { "Layout", "UI (Canvas)", "Physics", "Audio", "Effects", "Navigation" };

        /// <summary>
        /// Base types, interfaces and <c>[RequireComponent]</c> targets that put a component in a
        /// native root. Matched by full type name so no assembly reference is needed. Layout comes
        /// first because a layout driver also needs a <c>RectTransform</c>.
        /// </summary>
        private static readonly KeyValuePair<string, string[]>[] NativeMarkers =
        {
            // ILayoutElement is deliberately absent: every graphic implements it, and a graphic is
            // not a layout driver.
            new KeyValuePair<string, string[]>("Layout", new[]
            {
                "UnityEngine.UI.LayoutGroup", "UnityEngine.UI.ILayoutGroup", "UnityEngine.UI.ILayoutSelfController",
            }),
            new KeyValuePair<string, string[]>("UI (Canvas)", new[]
            {
                "UnityEngine.UI.Graphic", "UnityEngine.UI.MaskableGraphic", "UnityEngine.UI.Selectable",
                "UnityEngine.EventSystems.UIBehaviour", "UnityEngine.Canvas", "UnityEngine.RectTransform",
                "UnityEngine.CanvasRenderer", "UnityEngine.CanvasGroup", "TMPro.TMP_Text",
            }),
            new KeyValuePair<string, string[]>("Physics", new[]
            {
                "UnityEngine.Collider", "UnityEngine.Rigidbody", "UnityEngine.CharacterController",
                "UnityEngine.Joint", "UnityEngine.Cloth",
            }),
            new KeyValuePair<string, string[]>("Audio", new[]
            {
                "UnityEngine.AudioBehaviour", "UnityEngine.AudioSource", "UnityEngine.AudioListener",
                "UnityEngine.AudioLowPassFilter",
            }),
            new KeyValuePair<string, string[]>("Effects", new[]
            {
                "UnityEngine.ParticleSystem", "UnityEngine.TrailRenderer", "UnityEngine.LineRenderer",
                "UnityEngine.VFX.VisualEffect",
            }),
            new KeyValuePair<string, string[]>("Navigation", new[]
            {
                "UnityEngine.AI.NavMeshAgent", "UnityEngine.AI.NavMeshObstacle", "UnityEngine.AI.NavMeshSurface",
            }),
        };

        /// <summary>Framework folder (first segment inside a package) to the menu root that names it.</summary>
        private static readonly Dictionary<string, string> FrameworkRoots = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "com.aethernexus.foundationplatform/Runtime", "FoundationPlatform" },

            { "com.aethernexus.gameenginecore/Runtime", "GameEngineCore" },
            { "com.aethernexus.gameenginecore/_Shared", "GameEngineCore" },
            { "com.aethernexus.gameenginecore/Template", "GameEngineCore" },
            { "com.aethernexus.gameenginecore/UIWidgets", "UI Widgets" },
            { "com.aethernexus.gameenginecore/AudioEffectSystem", "Audio" },

            { "com.aethernexus.gameframework/AISystem", "AI System" },
            { "com.aethernexus.gameframework/CharacterSystem", "Character System" },
            { "com.aethernexus.gameframework/CombatSystem", "Combat System" },
            { "com.aethernexus.gameframework/ItemSystem", "Item System" },
            { "com.aethernexus.gameframework/QuestSystem", "Quest System" },

            { "com.aethernexus.gameplayabilitysystem/AbilitySystem", "Gameplay Ability System" },
            { "com.aethernexus.gameplayabilitysystem/AutoGenerated", "Gameplay Ability System" },
            { "com.aethernexus.gameplayabilitysystem/CommonAssets", "Gameplay Ability System" },
            { "com.aethernexus.gameplayabilitysystem/GameplayAttributeSystem", "Gameplay Ability System" },
            { "com.aethernexus.gameplayabilitysystem/GameplayCueSystem", "Gameplay Ability System" },
            { "com.aethernexus.gameplayabilitysystem/GameplayEffectSystem", "Gameplay Ability System" },
            { "com.aethernexus.gameplayabilitysystem/GameplayTagSystem", "Gameplay Tag System" },
            { "com.aethernexus.gameplayabilitysystem/UI", "Gameplay Ability System" },

            { "com.aethernexus.liveops/Economy", "Economy" },
            { "com.aethernexus.liveops/ShopSystem", "Shop" },
            { "com.aethernexus.liveops/TutorialModule", "Tutorial" },

            { "com.aethernexus.tacticalfeatures/Input", "Tactical Features" },
            { "com.aethernexus.tacticalfeatures/Party", "Tactical Features" },
            { "com.aethernexus.tacticalfeatures/Progression", "Tactical Features" },
            { "com.aethernexus.tacticalfeatures/Tactical", "Tactical Features" },
            { "com.aethernexus.tacticalfeatures/Targeting", "Tactical Features" },
            { "com.aethernexus.tacticalfeatures/Threat", "Tactical Features" },
        };

        /// <summary>Folder names that describe code layout rather than a designer-visible category.</summary>
        private static readonly HashSet<string> NoiseFolders = new HashSet<string>(StringComparer.Ordinal)
        {
            "Runtime", "Editor", "Scripts", "Source", "Src", "Systems", "System", "Components", "Component",
            "Core", "Behaviours", "Behaviors", "Authoring", "Utility", "Utilities", "Internal", "Base",
            "Common", "Shared", "_Shared", "Definitions", "Impl", "Implementation", "Controllers", "Views",
        };

        /// <summary>Folders whose designer-facing name differs from the folder name.</summary>
        private static readonly Dictionary<string, string> CategoryRenames = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "Diagnostics", "Debug" },
            { "Debugging", "Debug" },
            { "CardUI_Scripts", "Card UI" },
            { "Component_Scripts", "Widgets" },
            { "Panel_Scripts", "Panels" },
            { "Primitive_Scripts", "Primitives" },
            { "Sliders_Scripts", "Sliders" },
            { "ScrollList_Scripts", "Scroll List" },
            { "UIEffects", "Effects" },
            { "ToolTips", "Tooltips" },
        };

        /// <summary>Native root for a component that does a native category's job, or null.</summary>
        internal static string TryNativeRoot(Type type, IReadOnlyList<Type> requiredComponents)
        {
            var markers = new HashSet<string>(StringComparer.Ordinal);

            for (Type current = type; current != null; current = current.BaseType)
                markers.Add(current.FullName);

            foreach (Type contract in type.GetInterfaces())
                markers.Add(contract.FullName);

            foreach (Type required in requiredComponents)
            {
                for (Type current = required; current != null; current = current.BaseType)
                    markers.Add(current.FullName);
            }

            foreach (var rule in NativeMarkers)
            {
                foreach (string marker in rule.Value)
                {
                    if (markers.Contains(marker))
                        return rule.Key;
                }
            }

            return null;
        }

        /// <summary><c>Framework Name / Category / Type</c> for a component with no native home.</summary>
        internal static string ProductPath(Type type, string packageId, string scriptPath)
        {
            var segments = FolderSegments(packageId, scriptPath);
            string root = FrameworkRootFor(packageId, segments, type);
            string category = CategoryFor(segments);
            string leaf = Leaf(type.Name, root);

            // A category the root or the leaf already says is stutter, so the category goes rather
            // than words being cut out of the type's own name.
            if (Repeats(leaf, category) || Repeats(root, category))
                category = string.Empty;

            return string.IsNullOrEmpty(category) ? $"{root}/{leaf}" : $"{root}/{category}/{leaf}";
        }

        /// <summary>Leaf label under a native root: the humanized type name, product stutter removed.</summary>
        internal static string NativePath(Type type, string nativeRoot)
        {
            return $"{nativeRoot}/{Leaf(type.Name, nativeRoot)}";
        }

        private static List<string> FolderSegments(string packageId, string scriptPath)
        {
            string prefix = $"Packages/{packageId}/";
            string relative = scriptPath.Substring(prefix.Length);
            var segments = new List<string>(relative.Split('/'));
            segments.RemoveAt(segments.Count - 1);
            return segments;
        }

        private static string FrameworkRootFor(string packageId, List<string> segments, Type type)
        {
            if (segments.Count == 0)
                throw new InvalidOperationException(
                    $"'{type.FullName}' sits directly in {packageId} with no framework folder, so it has no menu root. Move it into a framework folder or give it an [AddComponentMenu] by hand.");

            string key = $"{packageId}/{segments[0]}";
            if (FrameworkRoots.TryGetValue(key, out string root))
                return root;

            throw new InvalidOperationException(
                $"No menu root is mapped for '{key}' (needed by {type.FullName}). Add it to {nameof(ComponentMenuTaxonomy)}.{nameof(FrameworkRoots)}.");
        }

        private static string CategoryFor(List<string> segments)
        {
            for (int i = 1; i < segments.Count; i++)
            {
                string segment = segments[i];
                if (NoiseFolders.Contains(segment))
                    continue;

                if (CategoryRenames.TryGetValue(segment, out string renamed))
                    return renamed;

                return Humanize(segment);
            }

            return string.Empty;
        }

        /// <summary>Type name as words, with a leading repeat of the root dropped so the path does not stutter.</summary>
        private static string Leaf(string typeName, string root)
        {
            var words = SplitWords(typeName);
            StripLeadingRepeat(words, root);

            return words.Count == 0 ? Humanize(typeName) : string.Join(" ", words);
        }

        private static bool Repeats(string owner, string category)
        {
            if (string.IsNullOrEmpty(category))
                return false;

            return owner.StartsWith(category, StringComparison.OrdinalIgnoreCase) ||
                   owner.EndsWith(category, StringComparison.OrdinalIgnoreCase) ||
                   category.StartsWith(owner, StringComparison.OrdinalIgnoreCase) ||
                   category.EndsWith(owner, StringComparison.OrdinalIgnoreCase);
        }

        private static void StripLeadingRepeat(List<string> words, string owner)
        {
            if (string.IsNullOrEmpty(owner))
                return;

            var ownerWords = new List<string>(owner.Replace("(", string.Empty).Replace(")", string.Empty).Split(' '));
            foreach (string ownerWord in ownerWords)
            {
                if (words.Count <= 1)
                    return;

                if (!string.Equals(words[0], ownerWord, StringComparison.OrdinalIgnoreCase))
                    return;

                words.RemoveAt(0);
            }
        }

        private static string Humanize(string name)
        {
            return string.Join(" ", SplitWords(name));
        }

        /// <summary>PascalCase to words, keeping runs of capitals together so acronyms survive (<c>UIWidget</c> -> <c>UI Widget</c>).</summary>
        private static List<string> SplitWords(string name)
        {
            var words = new List<string>(6);
            var current = new StringBuilder();

            for (int i = 0; i < name.Length; i++)
            {
                char c = name[i];
                if (!char.IsLetterOrDigit(c))
                {
                    if (current.Length > 0)
                    {
                        words.Add(current.ToString());
                        current.Clear();
                    }

                    continue;
                }

                char previous = current.Length > 0 ? current[current.Length - 1] : '\0';

                // "Drag2DHandler" -> "Drag2D Handler": a capital after a digit continues the word.
                bool boundary = current.Length > 0 && char.IsUpper(c) && !char.IsDigit(previous) &&
                                (!char.IsUpper(previous) ||
                                 (i + 1 < name.Length && char.IsLower(name[i + 1])));

                if (boundary)
                {
                    words.Add(current.ToString());
                    current.Clear();
                }

                current.Append(c);
            }

            if (current.Length > 0)
                words.Add(current.ToString());

            return words;
        }
    }
}
#endif
