#if UNITY_EDITOR
using System;
using UnityEngine;
using UnityEditor;
using System.Collections;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using AetherNexus.FoundationPlatform.DebugX;
using AetherNexus.FoundationPlatform.Editor.Animation;
using UnityEditor.Animations;
using UnityEngine.AI;
using UnityEngine.Rendering;
using AetherNexus.FoundationPlatform.Utilities.Menus;

public class Weaver : EditorWindow
{
    private const string FOLDER_LOCATION = "Scripts/AutoGenerated/";
    private const string TAGS_FILE_NAME = "Tags";
    private const string LAYERS_FILE_NAME = "Layers";
    private const string SORTING_LAYERS_FILE_NAME = "SortingLayers";
    private const string SCENES_FILE_NAME = "Scenes";
    private const string ANIMATIONS_FILE_NAME = "Animations";
    private const string NAVMESH_AREAS_FILE_NAME = "NavMeshAreas";
    private const string SHADERS_FILE_NAME = "Shaders";
    private const string SCRIPT_EXTENSION = ".g.cs";

    [MenuItem(MenuPaths.Rebuild.TagsLayersScenes, false, MenuPriorities.Rebuild)]
    static void RebuildTagsAndLayersClasses()
    {
        string folderPath = System.IO.Path.Combine(Application.dataPath, FOLDER_LOCATION);
        if (!Directory.Exists(folderPath))
        {
            Directory.CreateDirectory(folderPath);
        }

        bool tagsChanged = EditorCodegen.WriteIfChanged(
            System.IO.Path.Combine(folderPath, TAGS_FILE_NAME + SCRIPT_EXTENSION),
            GetConstStringClassContent(TAGS_FILE_NAME, UnityEditorInternal.InternalEditorUtility.tags));
        bool layersChanged = EditorCodegen.WriteIfChanged(
            System.IO.Path.Combine(folderPath, LAYERS_FILE_NAME + SCRIPT_EXTENSION),
            GetLayerClassContent(LAYERS_FILE_NAME, UnityEditorInternal.InternalEditorUtility.layers));
        bool sortingLayersChanged = EditorCodegen.WriteIfChanged(
            System.IO.Path.Combine(folderPath, SORTING_LAYERS_FILE_NAME + SCRIPT_EXTENSION),
            GetSortingLayerClassContent(SORTING_LAYERS_FILE_NAME, SortingLayer.layers.Select(x => x.name).ToArray()));
        bool scenesChanged = EditorCodegen.WriteIfChanged(
            System.IO.Path.Combine(folderPath, SCENES_FILE_NAME + SCRIPT_EXTENSION),
            GetConstStringClassContent(SCENES_FILE_NAME, EditorBuildSettingsScenesToNameStrings(EditorBuildSettings.scenes)));

        if (tagsChanged)
        {
            AssetDatabase.ImportAsset("Assets/" + FOLDER_LOCATION + TAGS_FILE_NAME + SCRIPT_EXTENSION, ImportAssetOptions.Default);
        }
        if (layersChanged)
        {
            AssetDatabase.ImportAsset("Assets/" + FOLDER_LOCATION + LAYERS_FILE_NAME + SCRIPT_EXTENSION, ImportAssetOptions.Default);
        }
        if (sortingLayersChanged)
        {
            AssetDatabase.ImportAsset("Assets/" + FOLDER_LOCATION + SORTING_LAYERS_FILE_NAME + SCRIPT_EXTENSION, ImportAssetOptions.Default);
        }
        if (scenesChanged)
        {
            AssetDatabase.ImportAsset("Assets/" + FOLDER_LOCATION + SCENES_FILE_NAME + SCRIPT_EXTENSION, ImportAssetOptions.Default);
        }
        DebugX.Debug("Layers, Tags and Scenes Rebuild Complete");
    }

    [MenuItem(MenuPaths.Rebuild.AllConstants, false, MenuPriorities.Rebuild + 4)]
    static void RebuildAll()
    {
        RebuildTagsAndLayersClasses();
        RebuildAnimationsConstants();
        AnimationSetCodeGenerator.RebuildAllAnimationSets();
        RebuildNavMeshAreasConstants();
        RebuildShadersConstants();
        DebugX.Debug("All constants rebuilt");
    }

    [MenuItem(MenuPaths.Rebuild.Animations, false, MenuPriorities.Rebuild + 1)]
    static void RebuildAnimationsConstants()
    {
        string folderPath = System.IO.Path.Combine(Application.dataPath, FOLDER_LOCATION);
        if (!Directory.Exists(folderPath))
        {
            Directory.CreateDirectory(folderPath);
        }
        bool changed = EditorCodegen.WriteIfChanged(
            System.IO.Path.Combine(folderPath, ANIMATIONS_FILE_NAME + SCRIPT_EXTENSION),
            GetAnimationsClassContent(ANIMATIONS_FILE_NAME));
        if (changed)
        {
            AssetDatabase.ImportAsset("Assets/" + FOLDER_LOCATION + ANIMATIONS_FILE_NAME + SCRIPT_EXTENSION, ImportAssetOptions.Default);
        }
        DebugX.Debug("Animations constants rebuild complete");
    }

    [MenuItem(MenuPaths.Rebuild.NavMeshAreas, false, MenuPriorities.Rebuild + 2)]
    static void RebuildNavMeshAreasConstants()
    {
        string folderPath = System.IO.Path.Combine(Application.dataPath, FOLDER_LOCATION);
        if (!Directory.Exists(folderPath))
        {
            Directory.CreateDirectory(folderPath);
        }
        bool changed = EditorCodegen.WriteIfChanged(
            System.IO.Path.Combine(folderPath, NAVMESH_AREAS_FILE_NAME + SCRIPT_EXTENSION),
            GetNavMeshAreasClassContent(NAVMESH_AREAS_FILE_NAME));
        if (changed)
        {
            AssetDatabase.ImportAsset("Assets/" + FOLDER_LOCATION + NAVMESH_AREAS_FILE_NAME + SCRIPT_EXTENSION, ImportAssetOptions.Default);
        }
        DebugX.Debug("NavMesh Areas constants rebuild complete");
    }

    [MenuItem(MenuPaths.Rebuild.Shaders, false, MenuPriorities.Rebuild + 3)]
    static void RebuildShadersConstants()
    {
        string folderPath = System.IO.Path.Combine(Application.dataPath, FOLDER_LOCATION);
        if (!Directory.Exists(folderPath))
        {
            Directory.CreateDirectory(folderPath);
        }
        bool changed = EditorCodegen.WriteIfChanged(
            System.IO.Path.Combine(folderPath, SHADERS_FILE_NAME + SCRIPT_EXTENSION),
            GetShadersClassContent(SHADERS_FILE_NAME));
        if (changed)
        {
            AssetDatabase.ImportAsset("Assets/" + FOLDER_LOCATION + SHADERS_FILE_NAME + SCRIPT_EXTENSION, ImportAssetOptions.Default);
        }
        Debug.Log("Shaders constants rebuild complete");
    }

    private static string[] EditorBuildSettingsScenesToNameStrings(EditorBuildSettingsScene[] scenes)
    {
        string[] sceneNames = new string[scenes.Length];
        for (int n = 0; n < sceneNames.Length; n++)
        {
            sceneNames[n] = System.IO.Path.GetFileNameWithoutExtension(scenes[n].path);
        }

        return sceneNames;
    }

    private static string GetConstStringClassContent(string className, string[] labelsArray)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// This class is auto-generated. Do not modify. (TagsLayersScenesBuilder.cs)");
        sb.AppendLine("public static class " + SanitizeIdentifier(className));
        sb.AppendLine("{");
        foreach (string label in labelsArray)
        {
            sb.Append('\t').AppendLine(BuildConstStringVariable(label));
        }
        sb.Append("}");
        return sb.ToString();
    }

    private static string GetLayerClassContent(string className, string[] labelsArray)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// This class is auto-generated. Do not modify. (TagsLayersScenesBuilder.cs)");
        sb.AppendLine("public static class " + SanitizeIdentifier(className));
        sb.AppendLine("{");
        foreach (string label in labelsArray)
        {
            sb.Append('\t').AppendLine(BuildConstStringVariable(label));
        }
        sb.AppendLine();
        var usedIntNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (string label in labelsArray)
        {
            string name = DisambiguateIdentifier(ToUpperCaseWithUnderscores(label) + "_INT", usedIntNames);
            sb.Append('\t')
              .Append("public const int ")
              .Append(name).Append(" = ")
              .Append(LayerMask.NameToLayer(label))
              .AppendLine(";");
        }
        sb.Append("}");
        return sb.ToString();
    }

    private static string GetSortingLayerClassContent(string className, string[] labelsArray)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// This class is auto-generated. Do not modify. (TagsLayersScenesBuilder.cs)");
        sb.AppendLine("public static class " + SanitizeIdentifier(className));
        sb.AppendLine("{");
        foreach (string label in labelsArray)
        {
            sb.Append('\t').AppendLine(BuildConstStringVariable(label));
        }
        sb.AppendLine();
        var usedIntNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (string label in labelsArray)
        {
            string name = DisambiguateIdentifier(ToUpperCaseWithUnderscores(label) + "_ID", usedIntNames);
            sb.Append('\t')
              .Append("public const int ")
              .Append(name).Append(" = ")
              .Append(SortingLayer.NameToID(label))
              .AppendLine(";");
        }
        sb.Append("}");
        return sb.ToString();
    }

    private static string DisambiguateIdentifier(string candidate, HashSet<string> used)
    {
        string result = candidate;
        int suffix = 1;
        while (!used.Add(result))
        {
            result = candidate + "_" + suffix;
            suffix++;
        }
        return result;
    }

    private static string BuildConstStringVariable(string varName)
    {
        return "public const string " + ToUpperCaseWithUnderscores(varName) + " = " + '"' + varName + '"' + ";";
    }

    private static string ToUpperCaseWithUnderscores(string input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return "_";
        }

        var sb = new System.Text.StringBuilder();
        char first = input[0];
        if (!char.IsLetter(first) && first != '_')
        {
            sb.Append('_');
        }
        sb.Append(NormalizeIdentifierChar(first));

        for (int n = 1; n < input.Length; n++)
        {
            char current = input[n];
            char previous = input[n - 1];
            bool shouldInsertUnderscore = (char.IsUpper(current) || current == ' ') && !char.IsUpper(previous) && previous != '_' && previous != ' ';
            if (shouldInsertUnderscore)
            {
                sb.Append('_');
            }
            if (current != ' ')
            {
                sb.Append(NormalizeIdentifierChar(current));
            }
        }

        return sb.ToString().ToUpper();
    }

    private static char NormalizeIdentifierChar(char c)
    {
        if (char.IsLetterOrDigit(c) || c == '_')
        {
            return c;
        }
        return '_';
    }

    private static string SanitizeIdentifier(string input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return "_";
        }
        var sb = new System.Text.StringBuilder();
        char first = input[0];
        if (!char.IsLetter(first) && first != '_')
        {
            sb.Append('_');
        }
        sb.Append(NormalizeIdentifierChar(first));
        for (int i = 1; i < input.Length; i++)
        {
            sb.Append(NormalizeIdentifierChar(input[i]));
        }
        return sb.ToString();
    }

    private static string GetAnimationsClassContent(string className)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// This class is auto-generated. Do not modify. (TagsLayersScenesBuilder.cs)");
        sb.AppendLine("public static class " + SanitizeIdentifier(className));
        sb.AppendLine("{");
        string[] controllerGuids = AssetDatabase.FindAssets("t:AnimatorController");
        foreach (string guid in controllerGuids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            var controller = AssetDatabase.LoadAssetAtPath<AnimatorController>(path);
            if (controller == null) continue;
            string controllerClass = ToUpperCaseWithUnderscores(controller.name);
            sb.Append('\t').AppendLine("public static class " + SanitizeIdentifier(controllerClass));
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tpublic static class PARAMETERS");
            sb.AppendLine("\t\t{");
            foreach (var param in controller.parameters)
            {
                sb.Append('\t').Append('\t').Append('\t').AppendLine(BuildConstStringVariable(param.name));
            }
            sb.AppendLine("\t\t}");
            var states = new HashSet<string>();
            for (int i = 0; i < controller.layers.Length; i++)
            {
                CollectStatesRecursive(controller.layers[i].stateMachine, states);
            }
            sb.AppendLine("\t\tpublic static class STATES");
            sb.AppendLine("\t\t{");
            foreach (var stateName in states)
            {
                sb.Append('\t').Append('\t').Append('\t').AppendLine(BuildConstStringVariable(stateName));
            }
            sb.AppendLine("\t\t}");
            sb.AppendLine("\t}");
        }
        sb.Append("}");
        return sb.ToString();
    }

    private static void CollectStatesRecursive(AnimatorStateMachine sm, HashSet<string> states)
    {
        foreach (var child in sm.states)
        {
            if (child.state != null)
            {
                states.Add(child.state.name);
            }
        }
        foreach (var sub in sm.stateMachines)
        {
            if (sub.stateMachine != null)
            {
                CollectStatesRecursive(sub.stateMachine, states);
            }
        }
    }

    private static string GetNavMeshAreasClassContent(string className)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// This class is auto-generated. Do not modify. (TagsLayersScenesBuilder.cs)");
        sb.AppendLine("public static class " + SanitizeIdentifier(className));
        sb.AppendLine("{");
        string[] areaNames = GetNavMeshAreaNamesSafe();
        foreach (var area in areaNames)
        {
            sb.Append('\t').AppendLine(BuildConstStringVariable(area));
        }
        sb.AppendLine();
        var usedIntNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var area in areaNames)
        {
            string name = DisambiguateIdentifier(ToUpperCaseWithUnderscores(area) + "_INDEX", usedIntNames);
            sb.Append('\t').Append("public const int ").Append(name).Append(" = ")
              .Append(NavMesh.GetAreaFromName(area)).AppendLine(";");
        }
        sb.Append("}");
        return sb.ToString();
    }

    private static string[] GetNavMeshAreaNamesSafe()
    {
        try
        {
            return NavMesh.GetAreaNames();
        }
        catch
        {
            return new[] { "Walkable", "Not Walkable", "Jump" };
        }
    }

    private static string GetShadersClassContent(string className)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// This class is auto-generated. Do not modify. (TagsLayersScenesBuilder.cs)");
        sb.AppendLine("public static class " + SanitizeIdentifier(className));
        sb.AppendLine("{");
        string[] shaderGuids = AssetDatabase.FindAssets("t:Shader");
        var usedClassNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (string guid in shaderGuids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            var shader = AssetDatabase.LoadAssetAtPath<Shader>(path);
            if (shader == null) continue;
            string baseName = ToUpperCaseWithUnderscores(shader.name.Replace('/', '_'));
            string candidate = SanitizeIdentifier(baseName);
            if (usedClassNames.Contains(candidate))
            {
                string fromPath = ToUpperCaseWithUnderscores(path.Replace('/', '_'));
                candidate = SanitizeIdentifier(fromPath);
            }
            if (usedClassNames.Contains(candidate))
            {
                candidate = candidate + "_" + guid.Substring(0, 8).ToUpperInvariant();
            }
            usedClassNames.Add(candidate);
            sb.Append('\t').AppendLine("public static class " + candidate);
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tpublic static class PROPERTIES");
            sb.AppendLine("\t\t{");
            int propCount = shader.GetPropertyCount();
            for (int i = 0; i < propCount; i++)
            {
                string propName = shader.GetPropertyName(i);
                sb.Append('\t').Append('\t').Append('\t').AppendLine(BuildConstStringVariable(propName));
            }
            sb.AppendLine("\t\t}");
            sb.AppendLine("\t\tpublic static class KEYWORDS");
            sb.AppendLine("\t\t{");
            try
            {
                var localKeywords = shader.keywordSpace.keywords;
                foreach (var kw in localKeywords)
                {
                    sb.Append('\t').Append('\t').Append('\t').AppendLine(BuildConstStringVariable(kw.name));
                }
            }
            catch { }
            sb.AppendLine("\t\t}");
            sb.AppendLine("\t}");
        }
        sb.Append("}");
        return sb.ToString();
    }
}
#endif