#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using AetherNexus.FoundationPlatform.AetherInspector;
using AetherNexus.FoundationPlatform.AetherInspector.Editor;
using AetherNexus.FoundationPlatform.Utilities.Menus;
using UnityEditor;
using UnityEngine;


// AutoBinder: Creates or updates a MonoBehaviour with public fields for selected component types,
// scans under a root GameObject's children in hierarchy order, generates fields inside a marked region,
// and assigns references in the Inspector. Supports dry-run and overwrite options.
namespace AetherNexus.FoundationPlatform.Editor.Windows
{
using AetherNexus.FoundationPlatform.DebugX;
	
public class AutoBinderToolWindow : EditorWindow
{
	private const string RegionStart = "// <AUTO-GENERATED FIELDS START>";
	private const string RegionEnd = "// <AUTO-GENERATED FIELDS END>";


	[Serializable]
	private class TypeSelection
	{
		public List<string> assemblyQualifiedTypeNames = new List<string>();

		public IEnumerable<Type> GetTypesSafe()
		{
			foreach (var name in assemblyQualifiedTypeNames)
			{
				var t = Type.GetType(name);
				if (t != null)
				{
					yield return t;
				}
			}
		}
	}

	// UI State
	[SerializeField] private GameObject rootObject;
	[SerializeField] private Vector2 scroll;
	[SerializeField] private TypeSelection selectedTypes = new TypeSelection();
	[SerializeField] private TypeSelection terminalTypes = new TypeSelection();
	[SerializeField] private int listPageIndex = 0;
	[SerializeField] private int listPageSize = 20;
	[SerializeField] private bool showSelectedTypesFoldout = true;
	[SerializeField] private bool showTerminalTypesFoldout = true;

	// Results preview
	private string previewGeneratedCode = string.Empty;


	[MenuItem(MenuPaths.WindowUtilities.AutoBinder, priority = MenuPriorities.WindowUtilities + 4)]
	public static void Open()
	{
		GetWindow<AutoBinderToolWindow>("Auto Binder");
	}

	private void OnGUI()
	{

		scroll = EditorGUILayout.BeginScrollView(scroll);
		bool skipRest = false;
		try
		{
			EditorGUILayout.LabelField("Root GameObject", EditorStyles.boldLabel);
			rootObject = (GameObject)EditorGUILayout.ObjectField(rootObject, typeof(GameObject), true);

			GUILayout.Space(8);
			DrawTypePicker();

			GUILayout.Space(8);
			if (GUILayout.Button("Generate Preview"))
			{
				RunBinding();
			}

			// Only show preview if root and types are valid
			if (rootObject == null)
			{
				ShowNotification(new GUIContent("Select a root GameObject"));
				skipRest = true;
			}
			var types = selectedTypes.GetTypesSafe().ToList();
			if (!skipRest && types.Count == 0)
			{
				ShowNotification(new GUIContent("Add at least one Component type"));
				skipRest = true;
			}

			if (!skipRest)
			{
				GUILayout.Space(12);
				GuiKit.Title("Generated Code (Copy and paste into your script)");
				GuiKit.InfoBox("This is the content that will be placed between the marked region. Copy and paste it into your script.");
				EditorGUILayout.TextArea(previewGeneratedCode, GUILayout.MinHeight(200));
			}
		}
		finally
		{
			EditorGUILayout.EndScrollView();
		}
	}


	private void DrawTypePicker()
	{
		EditorGUILayout.LabelField("Component Types", EditorStyles.boldLabel);

		// Selected Types Foldout
		showSelectedTypesFoldout = GuiKit.SectionFoldout(showSelectedTypesFoldout, "Selected Types");
		if (showSelectedTypesFoldout)
		{
			EditorGUI.indentLevel++;
			EditorGUILayout.BeginHorizontal();
			if (GUILayout.Button("Pick Types...", GUILayout.Height(20)))
			{
				AutoBinderTypePickerWindow.Show((types) =>
				{
					foreach (var t in types)
					{
						AddType(t);
					}
				});
			}
			EditorGUILayout.EndHorizontal();
			
			EditorGUILayout.BeginHorizontal();
			if (GUILayout.Button("Add All UI Types", GUILayout.Height(20)))
			{
				foreach (var t in GetAllUIComponentTypes())
				{
					AddType(t);
				}
			}
			if (GUILayout.Button("Clear List", GUILayout.Height(20)))
			{
				selectedTypes.assemblyQualifiedTypeNames.Clear();
				listPageIndex = 0;
			}
			EditorGUILayout.EndHorizontal();

			if (selectedTypes.assemblyQualifiedTypeNames.Count > 0)
			{
				EditorGUILayout.LabelField($"Selected: {selectedTypes.assemblyQualifiedTypeNames.Count}");

				// Pagination controls
				int total = selectedTypes.assemblyQualifiedTypeNames.Count;
				int totalPages = Mathf.Max(1, (int)Mathf.Ceil(total / (float)Mathf.Max(1, listPageSize)));
				listPageIndex = Mathf.Clamp(listPageIndex, 0, totalPages - 1);
				EditorGUILayout.BeginHorizontal();
				GUI.enabled = listPageIndex > 0;
				if (GUILayout.Button("< Prev", GUILayout.Width(60))) listPageIndex--;
				GUI.enabled = true;
				EditorGUILayout.LabelField($"Page {listPageIndex + 1}/{totalPages} (Size {listPageSize})");
				listPageSize = EditorGUILayout.IntField(listPageSize, GUILayout.Width(60));
				listPageSize = Mathf.Clamp(listPageSize, 5, 200);
				GUI.enabled = listPageIndex < totalPages - 1;
				if (GUILayout.Button("Next >", GUILayout.Width(60))) listPageIndex++;
				GUI.enabled = true;
				EditorGUILayout.EndHorizontal();

				int start = listPageIndex * Mathf.Max(1, listPageSize);
				int end = Mathf.Min(total, start + Mathf.Max(1, listPageSize));
				for (int i = start; i < end; i++)
				{
					var t = Type.GetType(selectedTypes.assemblyQualifiedTypeNames[i]);
					EditorGUILayout.BeginHorizontal();
					EditorGUILayout.LabelField(t != null ? t.FullName : selectedTypes.assemblyQualifiedTypeNames[i]);
					if (GUILayout.Button("Remove", GUILayout.Width(70)))
					{
						selectedTypes.assemblyQualifiedTypeNames.RemoveAt(i);
						GUIUtility.ExitGUI();
					}
					EditorGUILayout.EndHorizontal();
				}
			}
			EditorGUI.indentLevel--;
		}

		EditorGUILayout.Space(8);

		// Terminal Types Foldout
		showTerminalTypesFoldout = GuiKit.SectionFoldout(showTerminalTypesFoldout, "Terminal Types");
		if (showTerminalTypesFoldout)
		{
			EditorGUI.indentLevel++;
			GuiKit.InfoBox("Terminal types stop the search from traversing their children. Useful for UI components like Button that have standard child structures.");
			
			EditorGUILayout.BeginHorizontal();
			if (GUILayout.Button("Pick Terminal Types...", GUILayout.Height(20)))
			{
				AutoBinderTypePickerWindow.Show((types) =>
				{
					foreach (var t in types)
					{
						AddTerminalType(t);
					}
				});
			}
			if (GUILayout.Button("Add Common UI Terminals", GUILayout.Height(20)))
			{
				foreach (var t in GetCommonTerminalTypes())
				{
					AddTerminalType(t);
				}
			}
			EditorGUILayout.EndHorizontal();
			
			if (GUILayout.Button("Clear Terminal List", GUILayout.Height(20)))
			{
				terminalTypes.assemblyQualifiedTypeNames.Clear();
			}

			if (terminalTypes.assemblyQualifiedTypeNames.Count > 0)
			{
				EditorGUILayout.Space(4);
				foreach (var typeName in terminalTypes.assemblyQualifiedTypeNames)
				{
					var t = Type.GetType(typeName);
					EditorGUILayout.BeginHorizontal();
					EditorGUILayout.LabelField(t != null ? t.FullName : typeName);
					if (GUILayout.Button("Remove", GUILayout.Width(70)))
					{
						terminalTypes.assemblyQualifiedTypeNames.Remove(typeName);
						GUIUtility.ExitGUI();
					}
					EditorGUILayout.EndHorizontal();
				}
			}
			EditorGUI.indentLevel--;
		}

		EditorGUILayout.Space(4);
		GuiKit.InfoBox("Use UI picker/type selector to add component types. Only Component-derived types are supported.", InfoMessageType.None);
	}

	private IEnumerable<Type> GetAllUIComponentTypes()
	{
		var baseSet = TypeCache.GetTypesDerivedFrom<Component>()
			.Where(t => t.IsClass && !t.IsAbstract);
		
		// Define the specific UI types we want to include
		var wantedTypes = new HashSet<string>(new[] { 
			// Interactive UI elements (derived from Selectable)
			"Button",
			"Dropdown",
			"Toggle",
			"Slider",
			"ScrollRect",
			
			// Basic UI elements
			"ButtonX",
			"Image",
			"RawImage",
			"Text",
			
			// Layout elements
			"LayoutElement",
			"ContentSizeFitter",
			"VerticalLayoutGroup",
			"HorizontalLayoutGroup",
			"GridLayoutGroup",
			
			// Canvas components
			"Canvas",
			"CanvasScaler",
			"GraphicRaycaster",
			"CanvasGroup",
			
			// Input fields
			"InputField",
			
			// TMPro components
			"TextMeshProUGUI",
			"TMP_Text",
			"TMP_InputField",
			"TMP_Dropdown"
		});
		
		// Get only the specific types we want
		var result = baseSet.Where(t => wantedTypes.Contains(t.Name));
		
		DebugX.Debug($"UI Types selected: {string.Join(", ", result.Select(t => t.Name))}");
		return result;
	}

private class AutoBinderTypePickerWindow : EditorWindow
	{
		private Action<List<Type>> onPicked;
		private string search = string.Empty;
		private Vector2 scroll;
		private List<Type> allTypes;
		private HashSet<Type> selection = new HashSet<Type>();

		public static void Show(Action<List<Type>> callback)
		{
			var win = CreateInstance<AutoBinderTypePickerWindow>();
			win.onPicked = callback;
			win.titleContent = new GUIContent("Select Component Types");
			win.minSize = new Vector2(480, 420);
			win.ShowUtility();
		}

		private void OnEnable()
		{
			allTypes = TypeCache.GetTypesDerivedFrom<Component>()
				.Where(t => t.IsClass && !t.IsAbstract)
				.OrderBy(t => t.Namespace)
				.ThenBy(t => t.Name)
				.ToList();
		}

		private void OnGUI()
		{
			EditorGUILayout.Space(4);
			EditorGUILayout.BeginHorizontal();
			search = EditorGUILayout.TextField("Search", search);
			if (GUILayout.Button("Clear", GUILayout.Width(60))) search = string.Empty;
			EditorGUILayout.EndHorizontal();

			EditorGUILayout.Space(6);
			EditorGUILayout.BeginHorizontal();
			if (GUILayout.Button("Select All", GUILayout.Width(100)))
			{
				foreach (var t in Filtered()) selection.Add(t);
			}
			if (GUILayout.Button("Deselect All", GUILayout.Width(100)))
			{
				foreach (var t in Filtered()) selection.Remove(t);
			}
			GUILayout.FlexibleSpace();
			EditorGUILayout.EndHorizontal();

			scroll = EditorGUILayout.BeginScrollView(scroll);
			foreach (var t in Filtered())
			{
				EditorGUILayout.BeginHorizontal();
				bool isSel = selection.Contains(t);
				bool next = EditorGUILayout.Toggle(isSel, GUILayout.Width(18));
				if (next != isSel)
				{
					if (next) selection.Add(t); else selection.Remove(t);
				}
				EditorGUILayout.LabelField(t.FullName);
				EditorGUILayout.EndHorizontal();
			}
			EditorGUILayout.EndScrollView();

			EditorGUILayout.Space(8);
			EditorGUILayout.BeginHorizontal();
			if (GUILayout.Button("OK", GUILayout.Height(24)))
			{
				onPicked?.Invoke(selection.ToList());
				Close();
			}
			if (GUILayout.Button("Cancel", GUILayout.Height(24)))
			{
				Close();
			}
			EditorGUILayout.EndHorizontal();
		}

		private IEnumerable<Type> Filtered()
		{
			if (string.IsNullOrEmpty(search)) return allTypes;
			string s = search.Trim();
			return allTypes.Where(t => (t.FullName != null && t.FullName.IndexOf(s, StringComparison.OrdinalIgnoreCase) >= 0) || t.Name.IndexOf(s, StringComparison.OrdinalIgnoreCase) >= 0);
		}
	}

	private void AddType(Type type)
	{
		if (type == null) return;
		if (!typeof(Component).IsAssignableFrom(type)) return;
		
		// Don't add if it's a base type that we want to exclude
		var baseTypesToExclude = new HashSet<string>(new[] { "Selectable" });
		if (baseTypesToExclude.Contains(type.Name)) return;
		
		var aqn = type.AssemblyQualifiedName;
		
		// Check if we already have this type
		if (selectedTypes.assemblyQualifiedTypeNames.Contains(aqn)) return;
		
		// Check if we already have a derived type of this one
		bool hasChildType = selectedTypes.GetTypesSafe().Any(existingType => 
			existingType != type && existingType.IsSubclassOf(type));
		
		// Don't add base type if we already have a derived type
		if (hasChildType)
		{
			Debug.Log($"Skipping base type {type.Name} because we already have a derived type");
			return;
		}
		
		// Check if this is a derived type and we have its base type
		var baseTypesToRemove = selectedTypes.assemblyQualifiedTypeNames
			.Select(name => Type.GetType(name))
			.Where(t => t != null && type.IsSubclassOf(t))
			.ToList();
		
		// Remove any base types of this type
		foreach (var baseType in baseTypesToRemove)
		{
			Debug.Log($"Removing base type {baseType.Name} because we're adding derived type {type.Name}");
			selectedTypes.assemblyQualifiedTypeNames.Remove(baseType.AssemblyQualifiedName);
		}
		
		selectedTypes.assemblyQualifiedTypeNames.Add(aqn);
		Repaint();
	}

	private void AddTerminalType(Type type)
	{
		if (type == null) return;
		if (!typeof(Component).IsAssignableFrom(type)) return;
		var aqn = type.AssemblyQualifiedName;
		if (!terminalTypes.assemblyQualifiedTypeNames.Contains(aqn))
		{
			terminalTypes.assemblyQualifiedTypeNames.Add(aqn);
			Repaint();
		}
	}

	private IEnumerable<Type> GetCommonTerminalTypes()
	{
		var baseSet = TypeCache.GetTypesDerivedFrom<Component>()
			.Where(t => t.IsClass && !t.IsAbstract);

		// Common UI components that typically have standard child structures
		var names = new HashSet<string>(new[] 
		{ 
			"Button",           // Has Text/Image children
			"Dropdown",         // Has complex dropdown list structure
			"ScrollRect",       // Has viewport/content structure
			"InputField",       // Has text/placeholder children
			"TMP_Dropdown",     // TMPro version with similar structure
			"TMP_InputField",   // TMPro version with similar structure
			"Toggle",           // Has checkmark/label children
			"Slider"            // Has fill/handle children
		});

		return baseSet.Where(t => names.Contains(t.Name));
	}

	private void ClearPreviewData()
	{
		previewGeneratedCode = string.Empty;
		Repaint();
	}

	private void RunBinding()
	{
		ClearPreviewData();

		if (rootObject == null)
		{
			ShowNotification(new GUIContent("Select a root GameObject"));
			return;
		}
		var types = selectedTypes.GetTypesSafe().ToList();
		if (types.Count == 0)
		{
			ShowNotification(new GUIContent("Add at least one Component type"));
			return;
		}

		// Discover components under root in hierarchy order
		var discovery = DiscoverComponents(rootObject.transform, types);

		// Build code for region
		var codeRegion = BuildFieldsRegionCode(discovery);
		previewGeneratedCode = codeRegion;
	}


	private class Discovered
	{
		public Type type;
		public List<Component> components = new List<Component>();
		public string fieldName;
		public bool isList;
	}

	private List<Discovered> DiscoverComponents(Transform root, List<Type> targetTypes)
	{
		var result = new List<Discovered>();
		var terminalTypeSet = new HashSet<Type>(terminalTypes.GetTypesSafe());

		// Traverse hierarchy in order (breadth-first respects hierarchy order visually)
		var queue = new Queue<Transform>();
		queue.Enqueue(root);
		var allByType = targetTypes.ToDictionary(t => t, t => new List<Component>());

		while (queue.Count > 0)
		{
			var t = queue.Dequeue();
			bool isTerminal = false;

			// Check if this transform is a terminal type
			foreach (var terminalType in terminalTypeSet)
			{
				if (t.GetComponent(terminalType) != null)
				{
					isTerminal = true;
					break;
				}
			}

			// Helper function to check if a component's type is a base type of any other component on the same object
			bool ShouldIncludeComponent(Component component)
			{
				var componentType = component.GetType();

				// First check if this component type is a base type of any of our target types
				foreach (var targetType in targetTypes)
				{
					if (targetType != componentType && targetType.IsSubclassOf(componentType))
					{
						return false;
					}
				}

				// Then check the actual components on the object
				var allComponents = t.GetComponents<Component>();
				foreach (var otherComp in allComponents)
				{
					if (otherComp == component) continue;

					var otherType = otherComp.GetType();

					// If this component is a base type of another component on this object
					if (otherType.IsSubclassOf(componentType))
					{
						return false;
					}
				}

				return true;
			}

			// Collect components from current transform, filtering out base types
			foreach (var kvp in allByType.ToList())
			{
				var found = t.GetComponents(kvp.Key);
				if (found != null && found.Length > 0)
				{
					// Only include components that aren't base types of other components we care about
					var filteredComponents = found.Where(ShouldIncludeComponent);
					kvp.Value.AddRange(filteredComponents);
				}
			}

			// Only enqueue children if this is not a terminal component
			if (!isTerminal)
			{
				foreach (Transform child in t)
				{
					queue.Enqueue(child);
				}
			}
		}

		// Determine field names and whether they should be lists when components are siblings under same parent
		foreach (var kvp in allByType)
		{
			var comps = kvp.Value;
			if (comps.Count == 0) continue;

			// Group by immediate parent to detect sibling groups
			var byParent = comps.GroupBy(c => c.transform.parent).ToList();
			foreach (var group in byParent)
			{
				var list = group.ToList();
				var dis = new Discovered
				{
					type = kvp.Key,
					components = list,
					isList = list.Count > 1
				};
				dis.fieldName = GenerateFieldName(dis);
				result.Add(dis);
			}
		}

		// Keep deterministic order: by type name, then by first component hierarchy index
		result = result.OrderBy(r => r.type.Name).ThenBy(r => GetHierarchyOrderKey(r.components.First())) .ToList();
		return result;
	}

	private string GetHierarchyOrderKey(Component c)
	{
		// Build a stable, comparable key from sibling indices up the parent chain so the
		// resulting order reflects actual hierarchy position (root-to-leaf, top-to-bottom).
		var indices = new List<int>();
		var t = c.transform;
		while (t != null)
		{
			indices.Add(t.GetSiblingIndex());
			t = t.parent;
		}
		indices.Reverse();
		var sb = new StringBuilder();
		foreach (var index in indices)
		{
			sb.Append(index.ToString("D6"));
			sb.Append('/');
		}
		return sb.ToString();
	}

	private static string GetTransformPath(Transform t)
	{
		var sb = new StringBuilder();
		while (t != null)
		{
			sb.Insert(0, "/" + t.name);
			t = t.parent;
		}
		return sb.ToString();
	}

	private string GenerateFieldName(Discovered dis)
	{
		var type = dis.type;
		bool isUI = IsUIType(type);
		string coreName;
		if (dis.isList)
		{
			// For lists, base name on parent and type
			string parentName = dis.components.First().transform.parent != null ? dis.components.First().transform.parent.name : rootObject.name;
			coreName = MakeIdentifier(parentName) + type.Name;
		}
		else
		{
			string childName = dis.components.First().name;
			coreName = MakeIdentifier(childName);
			if (isUI)
			{
				coreName = coreName + type.Name;
			}
		}
		// Unity convention: public fields are camelCase typically; many teams prefer lowerCamelCase
		return Char.ToLowerInvariant(coreName[0]) + coreName.Substring(1);
	}

	private bool IsUIType(Type type)
	{
		// Treat UnityEngine.UI and TMPro as UI
		if (type.Namespace != null && (type.Namespace.StartsWith("UnityEngine.UI") || type.Namespace.StartsWith("TMPro"))) return true;
		// Common UI components even if outside namespaces
		var uiNames = new[] { "Button", "Image", "Text", "TMP_Text", "TMP_InputField", "Slider", "Toggle", "ScrollRect", "Dropdown" };
		return uiNames.Contains(type.Name);
	}

	private string MakeIdentifier(string name)
	{
		var sb = new StringBuilder();
		foreach (var ch in name)
		{
			if (char.IsLetterOrDigit(ch)) sb.Append(ch);
		}
		var id = sb.Length > 0 ? sb.ToString() : "field";
		// PascalCase of words
		id = string.Concat(id.Split(new[] { '_' }, StringSplitOptions.RemoveEmptyEntries).Select(w => Char.ToUpperInvariant(w[0]) + (w.Length > 1 ? w.Substring(1) : "")));
		return id;
	}

	private string BuildFieldsRegionCode(List<Discovered> discovered)
	{
		var sb = new StringBuilder();
		sb.AppendLine(RegionStart);
		foreach (var d in discovered)
		{
			if (d.isList)
			{
				sb.Append('\t').Append("public List<").Append(d.type.Name).Append(">").Append(' ').Append(d.fieldName).AppendLine(" = new List<" + d.type.Name + ">();");
			}
			else
			{
				sb.Append('\t').Append("public ").Append(d.type.Name).Append(' ').Append(d.fieldName).AppendLine(";");
			}
		}
		sb.Append(RegionEnd);
		return sb.ToString();
	}







}
}
#endif

