#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using AetherNexus.FoundationPlatform.Animation;
using AetherNexus.FoundationPlatform.Utilities.Menus;
using UnityEditor;
using UnityEngine;

namespace AetherNexus.FoundationPlatform.Editor.Animation
{
	public static class AnimationSetCodeGenerator
	{
		private const string OutputFolder = "Assets/Scripts/AutoGenerated/AnimationSets";

		[MenuItem(MenuPaths.Rebuild.AnimationSet)]
		public static void RebuildAnimationSetConstants()
		{
			RebuildAllAnimationSets();
			Debug.Log("[AnimationSetCodeGenerator] Animation set constants rebuild complete.");
		}

		public static void RebuildAllAnimationSets()
		{
			if (!Directory.Exists(OutputFolder))
				Directory.CreateDirectory(OutputFolder);

			var guids          = AssetDatabase.FindAssets("t:AnimationSet");
			var generatedPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

			foreach (var guid in guids)
			{
				var path = AssetDatabase.GUIDToAssetPath(guid);
				var set  = AssetDatabase.LoadAssetAtPath<AnimationSet>(path);
				if (set == null)
					continue;

				RebuildAnimationSet(set, generatedPaths);
			}

			PruneOrphanedGeneratedFiles(generatedPaths);
			AssetDatabase.Refresh();
		}

		public static void RebuildAnimationSet(AnimationSet set, HashSet<string> generatedPaths)
		{
			if (set == null)
				throw new ArgumentNullException(nameof(set));

			if (generatedPaths == null)
				generatedPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

			if (!Directory.Exists(OutputFolder))
				Directory.CreateDirectory(OutputFolder);

			var outputPath = Path.Combine(OutputFolder, SanitizeFileName(set.name) + ".Ids.g.cs");
			string content;
			try
			{
				content = GenerateSetClass(set);
			}
			catch (InvalidOperationException ex)
			{
				Debug.LogError($"[AnimationSetCodeGenerator] '{set.name}': {ex.Message}", set);
				return;
			}

			if (WriteIfChanged(outputPath, content))
				AssetDatabase.ImportAsset(outputPath.Replace('\\', '/'));

			generatedPaths.Add(Path.GetFullPath(outputPath));
		}

		private static void PruneOrphanedGeneratedFiles(HashSet<string> keepFullPaths)
		{
			if (!Directory.Exists(OutputFolder))
				return;

			foreach (var file in Directory.GetFiles(OutputFolder, "*.Ids.g.cs"))
			{
				if (!keepFullPaths.Contains(Path.GetFullPath(file)))
					File.Delete(file);
			}
		}

		private static string GenerateSetClass(AnimationSet set)
		{
			var entries   = CollectValidEntries(set, out var errors);
			foreach (var error in errors)
				Debug.LogError($"[AnimationSetCodeGenerator] '{set.name}': {error}", set);

			var className   = SanitizeClassName(set.name) + "Ids";
			var usedNames   = new HashSet<string>();
			var idToConst   = new Dictionary<string, string>(StringComparer.Ordinal);
			foreach (var entry in entries)
				idToConst[entry.Entry.id] = ToConstName(entry.Entry.id, usedNames);

			var profile = set.ResolvedBlendProfile;

			var sb = new StringBuilder();
			sb.AppendLine("// Auto-generated file - do not edit manually");
			sb.AppendLine("// Generated by AnimationSetCodeGenerator");
			sb.AppendLine();
			sb.AppendLine("namespace CharacterSystem.Animation");
			sb.AppendLine("{");
			sb.AppendLine($"\tpublic static class {className}");
			sb.AppendLine("\t{");
			sb.AppendLine($"\t\tpublic const string SetName = \"{EscapeString(set.name)}\";");
			sb.AppendLine();

			foreach (var entry in entries)
				sb.AppendLine($"\t\tpublic const string {idToConst[entry.Entry.id]} = \"{EscapeString(entry.Entry.id)}\";");

			sb.AppendLine();
			AppendStanceConstants(sb, profile);
			AppendRequiredClipConstants(sb, set, className, idToConst, usedNames);
			AppendCategoryEntryConstants(sb, set, className, idToConst, usedNames);
			AppendStanceMetadata(sb, profile, idToConst, usedNames);

			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}

		private static void AppendStanceConstants(
			StringBuilder sb,
			LocomotionBlendProfile profile)
		{
			sb.AppendLine("\t\tpublic static class LocomotionStanceIds");
			sb.AppendLine("\t\t{");

			if (profile != null && profile.stances != null && profile.stances.Length > 0)
			{
				var stanceConstNames = new HashSet<string>(StringComparer.Ordinal);
				foreach (var stance in profile.stances)
				{
					if (stance == null || string.IsNullOrWhiteSpace(stance.stanceId))
						continue;

					var constName = ToConstName(stance.stanceId, stanceConstNames);
					sb.AppendLine($"\t\t\tpublic const string {constName} = \"{EscapeString(stance.stanceId)}\";");
				}
			}

			sb.AppendLine("\t\t}");
			sb.AppendLine();
		}

		private static void AppendRequiredClipConstants(
			StringBuilder sb,
			AnimationSet set,
			string className,
			Dictionary<string, string> idToConst,
			HashSet<string> usedConstNames)
		{
			sb.AppendLine("\t\tpublic static class LocomotionClipCategories");
			sb.AppendLine("\t\t{");

			var validationProfile = set?.ResolvedValidationProfile;
			if (validationProfile?.requiredCategoryEntries != null && validationProfile.requiredCategoryEntries.Length > 0)
			{
				var seenCategories = new HashSet<string>(StringComparer.Ordinal);
				foreach (var clip in validationProfile.requiredCategoryEntries)
				{
					if (clip.category == null || string.IsNullOrWhiteSpace(clip.category) || string.IsNullOrWhiteSpace(clip.entryId))
						continue;

					var categoryConst = SanitizeIdentifierPreserveName(clip.category);
					if (string.IsNullOrWhiteSpace(categoryConst))
					{
						throw new InvalidOperationException(
							$"Invalid required clip category '{clip.category}' in validation profile '{validationProfile.name}'.");
					}

					if (!seenCategories.Add(categoryConst))
					{
						throw new InvalidOperationException(
							$"Duplicate required clip category '{clip.category}' in validation profile '{validationProfile.name}'.");
					}

					usedConstNames.Add("LocomotionClipCategories." + categoryConst);

					if (!idToConst.TryGetValue(clip.entryId, out var entryConst))
					{
						throw new InvalidOperationException(
							$"Required clip category '{clip.category}' references unknown entryId '{clip.entryId}'.");
					}

					sb.AppendLine($"\t\t\tpublic const string {categoryConst} = {className}.{entryConst};");
				}
			}

			sb.AppendLine("\t\t}");
			sb.AppendLine();
		}

		private static void AppendCategoryEntryConstants(
			StringBuilder sb,
			AnimationSet set,
			string className,
			Dictionary<string, string> idToConst,
			HashSet<string> usedConstNames)
		{
			if (set == null)
				return;

			var resolved = set.GetResolvedEntries();
			var byCategory = new Dictionary<string, List<AnimationSetEntry>>(StringComparer.Ordinal);
			foreach (var entry in resolved.Values)
			{
				if (entry == null || string.IsNullOrWhiteSpace(entry.category) || string.IsNullOrWhiteSpace(entry.id))
					continue;

				if (!byCategory.TryGetValue(entry.category, out var list))
				{
					list = new List<AnimationSetEntry>();
					byCategory[entry.category] = list;
				}

				list.Add(entry);
			}

			foreach (var pair in byCategory)
			{
				var categoryClass = SanitizeIdentifierPreserveName(pair.Key);
				if (string.IsNullOrWhiteSpace(categoryClass))
					continue;

				if (usedConstNames.Contains(categoryClass))
					continue;

				usedConstNames.Add(categoryClass);
				sb.AppendLine($"\t\tpublic static class {categoryClass}");
				sb.AppendLine("\t\t{");
				var classMemberNames = new HashSet<string>(StringComparer.Ordinal);
				foreach (var entry in pair.Value)
				{
					if (!idToConst.TryGetValue(entry.id, out var entryConst))
						continue;

					var memberName = ToConstName(entry.id, classMemberNames);
					sb.AppendLine($"\t\t\tpublic const string {memberName} = {className}.{entryConst};");
				}

				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}
		}

		private static void AppendStanceMetadata(
			StringBuilder sb,
			LocomotionBlendProfile profile,
			Dictionary<string, string> idToConst,
			HashSet<string> usedConstNames)
		{
			if (profile == null || profile.stances == null || profile.stances.Length == 0)
			{
				sb.AppendLine("\t\tpublic static readonly LocomotionStanceBlendMetadata[] StanceBlends = System.Array.Empty<LocomotionStanceBlendMetadata>();");
				return;
			}

			var arrayConstNames = new List<string>();
			for (var i = 0; i < profile.stances.Length; i++)
			{
				var stance    = profile.stances[i];
				var arrayName = ToConstName(stance.stanceId + "_BlendIds", usedConstNames);
				arrayConstNames.Add(arrayName);
				AppendStanceBlendArray(sb, arrayName, stance, idToConst);
			}

			sb.AppendLine("\t\tpublic static readonly LocomotionStanceBlendMetadata[] StanceBlends =");
			sb.AppendLine("\t\t{");
			for (var i = 0; i < profile.stances.Length; i++)
			{
				var stanceId    = profile.stances[i].stanceId;
				var stanceConst = ToConstName(stanceId, new HashSet<string>());
				sb.AppendLine(
					$"\t\t\tnew LocomotionStanceBlendMetadata(LocomotionStanceIds.{stanceConst}, {i}, {arrayConstNames[i]}),");
			}

			sb.AppendLine("\t\t};");
		}

		private static void AppendStanceBlendArray(
			StringBuilder sb,
			string arrayName,
			LocomotionBlendStanceDefinition stance,
			Dictionary<string, string> idToConst)
		{
			if (!stance.HasExplicitDirectionEntryIds())
			{
				sb.AppendLine($"\t\tpublic static readonly string[] {arrayName} = System.Array.Empty<string>();");
				return;
			}

			var constNames = new List<string>();
			var slotCount = stance.GetDirectionSlotCount();
			for (var d = 0; d < LocomotionBlendStanceDefinition.CardinalDirectionSlotCount; d++)
			{
				var entryId = stance.directionEntryIds[d];
				if (!idToConst.TryGetValue(entryId, out var entryConst))
				{
					constNames.Clear();
					break;
				}

				constNames.Add(entryConst);
			}

			if (constNames.Count == LocomotionBlendStanceDefinition.CardinalDirectionSlotCount && stance.enableDiagonalDirections)
			{
				for (var d = 0; d < LocomotionBlendStanceDefinition.DiagonalDirectionSlotCount; d++)
				{
					var entryId = stance.diagonalDirectionEntryIds[d];
					if (!idToConst.TryGetValue(entryId, out var entryConst))
					{
						constNames.Clear();
						break;
					}

					constNames.Add(entryConst);
				}
			}

			if (constNames.Count != slotCount)
			{
				sb.AppendLine($"\t\tpublic static readonly string[] {arrayName} = System.Array.Empty<string>();");
				return;
			}

			sb.AppendLine($"\t\tpublic static readonly string[] {arrayName} =");
			sb.AppendLine("\t\t{");
			for (var i = 0; i < constNames.Count; i++)
				sb.AppendLine($"\t\t\t{constNames[i]},");
			sb.AppendLine("\t\t};");
		}

		private sealed class EntryInfo
		{
			public AnimationSetEntry Entry;
		}


		private static List<EntryInfo> CollectValidEntries(AnimationSet set, out List<string> errors)
		{
			errors = new List<string>();
			var result  = new List<EntryInfo>();
			var seenIds = new HashSet<string>(StringComparer.Ordinal);

			if (set == null)
				return result;

			var resolved = set.GetResolvedEntries();
			foreach (var entry in resolved.Values)
			{
				if (entry == null || string.IsNullOrWhiteSpace(entry.id))
					continue;

				if (!seenIds.Add(entry.id))
				{
					errors.Add($"Duplicate entry id '{entry.id}'.");
					continue;
				}

				result.Add(new EntryInfo { Entry = entry });
			}

			return result;
		}

		private static string SanitizeClassName(string assetName)
		{
			var sb = new StringBuilder();
			if (string.IsNullOrEmpty(assetName))
				return "AnimationSet";

			var first = assetName[0];
			sb.Append(char.IsLetter(first) || first == '_' ? first : '_');
			for (var i = 1; i < assetName.Length; i++)
			{
				var c = assetName[i];
				sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
			}

			return sb.ToString();
		}

		private static string SanitizeFileName(string assetName) => SanitizeClassName(assetName);

		private static string ToConstName(string entryId, HashSet<string> usedConstNames)
		{
			if (string.IsNullOrEmpty(entryId))
				entryId = "entry";

			var sb = new StringBuilder();
			var capitalizeNext = true;
			for (var i = 0; i < entryId.Length; i++)
			{
				var c = entryId[i];
				if (c == '_')
				{
					sb.Append('_');
					capitalizeNext = true;
				}
				else if (char.IsLetterOrDigit(c))
				{
					if (capitalizeNext)
					{
						sb.Append(char.ToUpperInvariant(c));
						capitalizeNext = false;
					}
					else
					{
						sb.Append(c);
					}
				}
				else
				{
					sb.Append('_');
					capitalizeNext = true;
				}
			}

			// Ensure first character is valid for C# identifier
			if (sb.Length > 0 && char.IsDigit(sb[0]))
			{
				sb.Insert(0, '_');
			}

			var baseName  = sb.ToString();
			var candidate = baseName;
			var n         = 1;
			while (!usedConstNames.Add(candidate))
			{
				candidate = baseName + "_" + n;
				n++;
			}

			return candidate;
		}

		private static string SanitizeIdentifierPreserveName(string value)
		{
			if (string.IsNullOrWhiteSpace(value))
				return string.Empty;

			var sb = new StringBuilder(value.Length);
			var first = value[0];
			sb.Append(char.IsLetter(first) || first == '_' ? first : '_');
			for (var i = 1; i < value.Length; i++)
			{
				var c = value[i];
				sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
			}

			return sb.ToString();
		}

private static string EscapeString(string value) =>
			value.Replace("\\", "\\\\").Replace("\"", "\\\"");

		private static bool WriteIfChanged(string path, string content)
		{
			try
			{
				if (File.Exists(path))
				{
					var existing = File.ReadAllText(path);
					if (string.Equals(existing, content, StringComparison.Ordinal))
						return false;
				}

				File.WriteAllText(path, content);
				return true;
			}
			catch (Exception e)
			{
				Debug.LogError($"[AnimationSetCodeGenerator] Failed to write '{path}': {e}");
				return false;
			}
		}
	}
}
#endif
