#if UNITY_EDITOR
using System;
using System.IO;
using System.Text;
using AetherNexus.FoundationPlatform.Animation;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace AetherNexus.FoundationPlatform.Editor.Animation
{
    internal static class AnimatorConstantsGenerator
    {
        private const string RegionStartMarker = "// <auto-generated AnimatorConstants>";
        private const string RegionEndMarker = "// </auto-generated AnimatorConstants>";

        public static void GenerateConstants(AnimatorBridgeBase bridgeBase)
        {
            if (bridgeBase == null)
            {
                return;
            }

            var animator = bridgeBase.GetComponent<Animator>();
            if (animator == null)
            {
                Debug.LogWarning($"{nameof(AnimatorConstantsGenerator)}: No Animator found on GameObject '{bridgeBase.gameObject.name}'.");
                return;
            }

            if (!(animator.runtimeAnimatorController is AnimatorController controller))
            {
                Debug.LogWarning(
                    $"{nameof(AnimatorConstantsGenerator)}: Animator on '{bridgeBase.gameObject.name}' does not use an AnimatorController that can be inspected in the editor.");
                return;
            }

            var monoScript = MonoScript.FromMonoBehaviour(bridgeBase);
            if (monoScript == null)
            {
                Debug.LogWarning($"{nameof(AnimatorConstantsGenerator)}: Could not locate MonoScript for bridgeBase type '{bridgeBase.GetType().Name}'.");
                return;
            }

            var scriptPath = AssetDatabase.GetAssetPath(monoScript);
            if (string.IsNullOrEmpty(scriptPath) || !File.Exists(scriptPath))
            {
                Debug.LogWarning($"{nameof(AnimatorConstantsGenerator)}: Could not resolve script path for '{monoScript.name}'.");
                return;
            }

            string source;
            try
            {
                source = File.ReadAllText(scriptPath);
            }
            catch (Exception ex)
            {
                Debug.LogError($"{nameof(AnimatorConstantsGenerator)}: Failed to read script file at '{scriptPath}'. Exception: {ex}");
                return;
            }

            var regionStartIndex = source.IndexOf(RegionStartMarker, StringComparison.Ordinal);
            var regionEndIndex = source.IndexOf(RegionEndMarker, StringComparison.Ordinal);

            if (regionStartIndex < 0 || regionEndIndex < 0 || regionEndIndex < regionStartIndex)
            {
                Debug.LogWarning(
                    $"{nameof(AnimatorConstantsGenerator)}: Auto-generated region markers not found in script '{scriptPath}'. " +
                    $"Expected '{RegionStartMarker}' and '{RegionEndMarker}' inside the concrete bridgeBase class.");
                return;
            }

            // Build the generated code for parameters, layers, and states.
            var generated = BuildGeneratedRegion(bridgeBase.GetType().Name, controller);

            // Keep everything up to and including the start marker, then insert generated code,
            // then keep everything from the end marker onwards.
            var afterStart = regionStartIndex + RegionStartMarker.Length;

            var before = source.Substring(0, afterStart);
            var after = source.Substring(regionEndIndex);

            var newSource = new StringBuilder(before.Length + generated.Length + after.Length);
            newSource.Append(before);
            newSource.AppendLine();
            newSource.Append(generated);
            newSource.AppendLine();
            newSource.Append(after);

            try
            {
                File.WriteAllText(scriptPath, newSource.ToString(), Encoding.UTF8);
                AssetDatabase.Refresh();
                Debug.Log($"{nameof(AnimatorConstantsGenerator)}: Regenerated animator constants for '{bridgeBase.GetType().Name}' at '{scriptPath}'.");
            }
            catch (Exception ex)
            {
                Debug.LogError($"{nameof(AnimatorConstantsGenerator)}: Failed to write script file at '{scriptPath}'. Exception: {ex}");
            }
        }

        private static string BuildGeneratedRegion(string handlerTypeName, AnimatorController controller)
        {
            // We generate nested static classes with static readonly int hashes.
            // These sit inside the concrete handler class and are fully overwritten
            // every time the generator runs.
            var sb = new StringBuilder();

            sb.AppendLine("\t\t// Auto-generated from AnimatorController '" + controller.name + "'.");
            sb.AppendLine("\t\t// This section will be overwritten when running 'Regenerate Animator Constants'.");

            // Parameters -> ParamHashes
            sb.AppendLine("\t\tpublic static class ParamHashes");
            sb.AppendLine("\t\t{");
            foreach (var parameter in controller.parameters)
            {
                var identifier = SanitizeIdentifier(parameter.name);
                if (string.IsNullOrEmpty(identifier))
                {
                    continue;
                }

                sb.AppendLine(
                    $"\t\t\tpublic static readonly int {identifier} = Animator.StringToHash(\"{parameter.name}\");");
            }
            sb.AppendLine("\t\t}");
            sb.AppendLine();

            // Parameters -> ParamNames
            sb.AppendLine("\t\tpublic static class ParamNames");
            sb.AppendLine("\t\t{");
            foreach (var parameter in controller.parameters)
            {
                var identifier = SanitizeIdentifier(parameter.name);
                if (string.IsNullOrEmpty(identifier))
                {
                    continue;
                }

                sb.AppendLine(
                    $"\t\t\tpublic const string {identifier} = \"{parameter.name}\";");
            }
            sb.AppendLine("\t\t}");
            sb.AppendLine();

            // Layers -> LayerHashes
            sb.AppendLine("\t\tpublic static class LayerHashes");
            sb.AppendLine("\t\t{");
            for (var i = 0; i < controller.layers.Length; i++)
            {
                var layer = controller.layers[i];
                var identifier = SanitizeIdentifier(layer.name);
                if (string.IsNullOrEmpty(identifier))
                {
                    identifier = "Layer" + i;
                }

                sb.AppendLine(
                    $"\t\t\tpublic static readonly int {identifier} = Animator.StringToHash(\"{layer.name}\");");
            }
            sb.AppendLine("\t\t}");
            sb.AppendLine();

            // Layers -> LayerNames
            sb.AppendLine("\t\tpublic static class LayerNames");
            sb.AppendLine("\t\t{");
            for (var i = 0; i < controller.layers.Length; i++)
            {
                var layer = controller.layers[i];
                var identifier = SanitizeIdentifier(layer.name);
                if (string.IsNullOrEmpty(identifier))
                {
                    identifier = "Layer" + i;
                }

                sb.AppendLine(
                    $"\t\t\tpublic const string {identifier} = \"{layer.name}\";");
            }
            sb.AppendLine("\t\t}");
            sb.AppendLine();

            // States -> StateHashes
            sb.AppendLine("\t\tpublic static class StateHashes");
            sb.AppendLine("\t\t{");
            var stateHashFieldNames = new System.Collections.Generic.HashSet<string>(StringComparer.Ordinal);
            for (var i = 0; i < controller.layers.Length; i++)
            {
                var layer = controller.layers[i];
                var layerName = layer.name;
                var stateMachine = layer.stateMachine;

                foreach (var childState in stateMachine.states)
                {
                    var state = childState.state;
                    var stateName = state.name;

                    // We use the full path "LayerName.StateName" for the hash, which is
                    // a common pattern for unique animator state hashing.
                    var fullPath = layerName + "." + stateName;
                    var identifier = SanitizeIdentifier(stateName);
                    if (string.IsNullOrEmpty(identifier))
                    {
                        continue;
                    }

                    var fieldName = identifier;
                    if (!string.IsNullOrEmpty(layerName))
                    {
                        fieldName = SanitizeIdentifier(layerName) + "_" + identifier;
                    }

                    fieldName = DisambiguateName(fieldName, stateHashFieldNames);

                    sb.AppendLine(
                        $"\t\t\tpublic static readonly int {fieldName} = Animator.StringToHash(\"{fullPath}\");");
                }
            }
            sb.AppendLine("\t\t}");
            sb.AppendLine();

            // States -> StateNames
            sb.AppendLine("\t\tpublic static class StateNames");
            sb.AppendLine("\t\t{");
            var stateNameFieldNames = new System.Collections.Generic.HashSet<string>(StringComparer.Ordinal);
            for (var i = 0; i < controller.layers.Length; i++)
            {
                var layer = controller.layers[i];
                var layerName = layer.name;
                var stateMachine = layer.stateMachine;

                foreach (var childState in stateMachine.states)
                {
                    var state = childState.state;
                    var stateName = state.name;

                    var identifier = SanitizeIdentifier(stateName);
                    if (string.IsNullOrEmpty(identifier))
                    {
                        continue;
                    }

                    var fieldName = identifier;
                    if (!string.IsNullOrEmpty(layerName))
                    {
                        fieldName = SanitizeIdentifier(layerName) + "_" + identifier;
                    }

                    fieldName = DisambiguateName(fieldName, stateNameFieldNames);

                    sb.AppendLine(
                        $"\t\t\tpublic const string {fieldName} = \"{stateName}\";");
                }
            }
            sb.AppendLine("\t\t}");

            return sb.ToString();
        }

        private static string DisambiguateName(string baseName, System.Collections.Generic.HashSet<string> usedNames)
        {
            var candidate = baseName;
            var n = 1;
            while (!usedNames.Add(candidate))
            {
                candidate = baseName + "_" + n;
                n++;
            }

            return candidate;
        }

        private static string SanitizeIdentifier(string rawName)
        {
            if (string.IsNullOrEmpty(rawName))
            {
                return string.Empty;
            }

            var sb = new StringBuilder(rawName.Length);
            foreach (var ch in rawName)
            {
                if (char.IsLetterOrDigit(ch) || ch == '_')
                {
                    sb.Append(ch);
                }
                else
                {
                    sb.Append('_');
                }
            }

            if (sb.Length == 0)
            {
                return string.Empty;
            }

            if (!char.IsLetter(sb[0]) && sb[0] != '_')
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }
    }
}
#endif
